### ISSUE TITLE
V6 and T-moble LG phone

### ISSUE THREAD

**Issue by ethycattygame** [SMIPE444/Infinity-Cheat#2]
It works but every time I research it crash. came back and research travel around map.CRASH AGEN! I think it is my v5 mod? Or that. After inf. Crash(I reset phone) I go at modminu remove v5 mod keep v6 mod. an after comeback CRASH INSTINT! I do no why.
(I think mod update will crash game.)

**Comment by ethycattygame** [comment]
Now I'm upset for not testing phone with this mod.
Is crashing crash crash crash-crash-crash-crash.

**Comment by ethycattygame** [comment]
And why. I got that mod https://github.com/MasterNo2/Techdustry

**Comment by MasterNo2** [comment]
Can you send me a copy of the crash report?
This should help me be able to better identify the problem. Also keep in mind I am still working on Techdustry before I plan for a full release. It used to be a V5 mod, but I want to furnish it for V6 and clean up all the rough edges for it. If you have any other problems, or any suggestions, let me know.

**Comment by SMIPE444** [comment]
@ethycattygame My mod is fully tested mod . Give me crash log then I can help you .

**Comment by 7d9** [comment]
how do you download this mod without downloading every asset yourself

**Comment by ethycattygame** [comment]
> how do you download this mod without downloading every asset yourself

copy link and crt+v at "add mod at github"(in game)

**Comment by MasterNo2** [comment]
Open the mods tab, then import mod. Then import from github. Type “ModMakersGithubName”/“ModName”
